# Generated by Django 3.0.7 on 2020-11-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('semestre', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Famille_competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_court', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParametresGeneaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_page', models.CharField(default='GEII', max_length=50)),
                ('nom_etablissement', models.CharField(default='Nom Etablissement', max_length=100)),
                ('auteurs', models.CharField(default='Nom Prénom', max_length=100)),
                ('annee_droits', models.CharField(default='2020', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='slides')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_court', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.FileField(upload_to='systemes/')),
                ('sysml', models.BooleanField(default=False)),
                ('matiere', models.ManyToManyField(blank=True, to='ressources.Matiere')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_court', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('numero', models.IntegerField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Matiere')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('github_prefix', models.CharField(default='', max_length=10, null=True)),
                ('competence', models.ManyToManyField(to='ressources.Competence')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Sequence')),
                ('systeme', models.ManyToManyField(blank=True, to='ressources.Systeme')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Ilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Ressource')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Systeme')),
            ],
            options={
                'ordering': ['parent', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='competence',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Famille_competence'),
        ),
        migrations.AddField(
            model_name='competence',
            name='matiere',
            field=models.ManyToManyField(to='ressources.Matiere'),
        ),
        migrations.AddField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_competence_parent_+', to='ressources.Competence'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
            ],
            options={
                'ordering': ['sequence', 'numero'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='Khole',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='Td',
            fields=[
            ],
            options={
                'ordering': ['sequence', 'numero'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='Tp',
            fields=[
            ],
            options={
                'ordering': ['sequence', 'numero'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.Ressource')),
                ('nom_fichier', models.CharField(max_length=100)),
                ('ressource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressource_associee', to='ressources.Ressource')),
            ],
            bases=('ressources.ressource',),
        ),
    ]
