# Generated by Django 3.0.7 on 2020-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('C', 'Cours'), ('KH', 'Khole'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('V', 'Video')], default='C', max_length=2),
            preserve_default=False,
        ),
    ]
