# Generated by Django 3.0.7 on 2020-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_ressource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='github_prefix',
        ),
        migrations.AddField(
            model_name='parametresgeneaux',
            name='github',
            field=models.CharField(default='https://github.com/', max_length=150),
        ),
    ]
